"""add goods orders and toss payment

Revision ID: df817ec37b80
Revises: 7b2e9a4c1f60
Create Date: 2026-10-02 10:51:11.347056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df817ec37b80'
down_revision = '7b2e9a4c1f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_product_price_nonnegative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_product_stock_quantity_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_product_sku')
    )
    op.create_table('product_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'product_id',
        'category',
        name='uq_product_category_product_category',
    )
    )
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_product_category_category'),
            ['category'],
            unique=False,
        )

    op.create_table('goods_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=50), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('address_detail', sa.String(length=255), nullable=True),
    sa.Column('delivery_request', sa.String(length=255), nullable=True),
    sa.Column('items_amount', sa.Integer(), nullable=False),
    sa.Column('shipping_fee', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='PAYMENT_PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('items_amount >= 0', name='ck_goods_order_items_amount_nonnegative'),
    sa.CheckConstraint('shipping_fee >= 0', name='ck_goods_order_shipping_fee_nonnegative'),
    sa.CheckConstraint('total_amount >= 0', name='ck_goods_order_total_amount_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number', name='uq_goods_order_order_number')
    )
    with op.batch_alter_table('goods_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_order_expires_at'), ['expires_at'], unique=False)

    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_product_image_sort_order_nonnegative'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'sort_order', name='uq_product_image_product_sort_order')
    )
    op.create_table('goods_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 1', name='ck_goods_order_item_quantity_positive'),
    sa.CheckConstraint('subtotal >= 0', name='ck_goods_order_item_subtotal_nonnegative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_goods_order_item_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['goods_order_id'], ['goods_order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goods_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('merchant_order_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=20), server_default='TOSS', nullable=False))
        batch_op.add_column(sa.Column('payment_key', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failure_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('failure_message', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=64), nullable=True))
        batch_op.alter_column('reservation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True)
        batch_op.create_unique_constraint(
            'uq_payment_goods_order_id', ['goods_order_id']
        )
        batch_op.create_unique_constraint(
            'uq_payment_idempotency_key', ['idempotency_key']
        )
        batch_op.create_unique_constraint(
            'uq_payment_payment_key', ['payment_key']
        )
        batch_op.create_unique_constraint(
            'uq_payment_merchant_order_id', ['merchant_order_id']
        )
        batch_op.create_foreign_key(
            'fk_payment_goods_order_id_goods_order',
            'goods_order',
            ['goods_order_id'],
            ['id'],
        )
        batch_op.create_check_constraint(
            'ck_payment_exactly_one_target',
            '(reservation_id IS NOT NULL AND goods_order_id IS NULL) OR '
            '(reservation_id IS NULL AND goods_order_id IS NOT NULL)',
        )
        batch_op.create_check_constraint(
            'ck_payment_amount_nonnegative',
            'amount >= 0',
        )

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_reservation_expires_at'), ['expires_at'], unique=False)
        batch_op.alter_column(
            'status',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
            server_default='PAYMENT_PENDING',
            existing_nullable=False,
        )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_customer_key', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(
            'uq_user_payment_customer_key', ['payment_customer_key']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_user_payment_customer_key', type_='unique'
        )
        batch_op.drop_column('payment_customer_key')

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
            server_default='PENDING',
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f('ix_reservation_expires_at'))
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(
            'ck_payment_amount_nonnegative', type_='check'
        )
        batch_op.drop_constraint(
            'ck_payment_exactly_one_target', type_='check'
        )
        batch_op.drop_constraint(
            'fk_payment_goods_order_id_goods_order', type_='foreignkey'
        )
        batch_op.drop_constraint(
            'uq_payment_merchant_order_id', type_='unique'
        )
        batch_op.drop_constraint(
            'uq_payment_payment_key', type_='unique'
        )
        batch_op.drop_constraint(
            'uq_payment_idempotency_key', type_='unique'
        )
        batch_op.drop_constraint(
            'uq_payment_goods_order_id', type_='unique'
        )
        batch_op.execute(
            sa.text("DELETE FROM payment WHERE goods_order_id IS NOT NULL")
        )
        batch_op.execute(
            sa.text(
                "UPDATE payment SET payment_method = 'UNKNOWN' "
                "WHERE payment_method IS NULL"
            )
        )
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False)
        batch_op.alter_column('reservation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('failure_message')
        batch_op.drop_column('failure_code')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('requested_at')
        batch_op.drop_column('payment_key')
        batch_op.drop_column('provider')
        batch_op.drop_column('merchant_order_id')
        batch_op.drop_column('goods_order_id')

    op.drop_table('goods_order_item')
    op.drop_table('product_image')
    with op.batch_alter_table('goods_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_order_expires_at'))

    op.drop_table('goods_order')
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_category_category'))

    op.drop_table('product_category')
    op.drop_table('product')
    # ### end Alembic commands ###
